{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leoxian.moonlightcore",
    "module": "moonlightcore-fabric",
    "version": "26.1.2.6-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "moonlightcore-fabric-26.1.2.6-beta.jar",
          "url": "moonlightcore-fabric-26.1.2.6-beta.jar",
          "size": 482496,
          "sha512": "367208447ae58ff7d679a5f0c25736c1b26567e175d6e4aec15168c657e8de524193dd4882ed90d1adc5dc1c5de7349d5aecbc1d3402bf0584a9f8468f55e472",
          "sha256": "2c98f92fd425bc903247286d29b0df35ced42d69a13ee375f86802e383766387",
          "sha1": "a11084ece2f92466bce1a7b6d85749a66712750b",
          "md5": "2472fe427d7041d962026939067fc559"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.149.0+26.1.2"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "moonlightcore-fabric-26.1.2.6-beta.jar",
          "url": "moonlightcore-fabric-26.1.2.6-beta.jar",
          "size": 482496,
          "sha512": "367208447ae58ff7d679a5f0c25736c1b26567e175d6e4aec15168c657e8de524193dd4882ed90d1adc5dc1c5de7349d5aecbc1d3402bf0584a9f8468f55e472",
          "sha256": "2c98f92fd425bc903247286d29b0df35ced42d69a13ee375f86802e383766387",
          "sha1": "a11084ece2f92466bce1a7b6d85749a66712750b",
          "md5": "2472fe427d7041d962026939067fc559"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-fabric-26.1.2.6-beta-sources.jar",
          "url": "moonlightcore-fabric-26.1.2.6-beta-sources.jar",
          "size": 212320,
          "sha512": "fbc5875de372fc93469ca39d41a16f0ccf3e4fd068185b9ba761a14be1ea4a2f9021e6d1ba20f0aab1409f62aa5e99d63c27972192dc9c234578f1ec7660dbe0",
          "sha256": "5686d9716727a0135d149f03d7c07fc32bc7ef2ef12bfbe9db3727afb351ce9e",
          "sha1": "a204f07da289bf1c425bfc30fa32a07093fca89e",
          "md5": "70ef0763176e681c96d6b2626a968b50"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-fabric-26.1.2.6-beta-javadoc.jar",
          "url": "moonlightcore-fabric-26.1.2.6-beta-javadoc.jar",
          "size": 5624366,
          "sha512": "a1fe0fbfa7083a8d5f05ec347784205614da8eea6e4f773960d33f5047e94811ab045d18c571e982131c1fca0eb676ecf92768cc8019583bf2e3af1188e29c00",
          "sha256": "f4907f3150a4b6cdd055fa79c15a3239c069ba7593d763f3a6f0b947704fa5c0",
          "sha1": "4c97729ab0c8df9cafc362954e994c2aca4d747b",
          "md5": "a5acd7301e01191b23fecc9e3cc35ee4"
        }
      ]
    }
  ]
}
