{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leoxian.moonlightcore",
    "module": "moonlightcore-xplat",
    "version": "26.1.2.7-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "moonlightcore-xplat-26.1.2.7-beta.jar",
          "url": "moonlightcore-xplat-26.1.2.7-beta.jar",
          "size": 354750,
          "sha512": "ba5aa3037e156b1f350cd8cab13e2aae18cabd5badd2d1717d924c1faeb2e301d02e6977abf322e0d24b98beb125417b3914ae2c4d6651352d0036c19aca1a12",
          "sha256": "2fcbaeac6cc27d75e4d6f471c7104d084ddb307ace2af8a131661d2113afce59",
          "sha1": "fb9850b54f0a94c860df047222c97b088eda601c",
          "md5": "0973aef53061e17566933afc74e9272b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-xplat-26.1.2.7-beta.jar",
          "url": "moonlightcore-xplat-26.1.2.7-beta.jar",
          "size": 354750,
          "sha512": "ba5aa3037e156b1f350cd8cab13e2aae18cabd5badd2d1717d924c1faeb2e301d02e6977abf322e0d24b98beb125417b3914ae2c4d6651352d0036c19aca1a12",
          "sha256": "2fcbaeac6cc27d75e4d6f471c7104d084ddb307ace2af8a131661d2113afce59",
          "sha1": "fb9850b54f0a94c860df047222c97b088eda601c",
          "md5": "0973aef53061e17566933afc74e9272b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-xplat-26.1.2.7-beta-sources.jar",
          "url": "moonlightcore-xplat-26.1.2.7-beta-sources.jar",
          "size": 158123,
          "sha512": "fb3cb07c145044cb3d2afc7954b59201e9081a8fe7fbf63eaa9071632db8a9b8748b96dc9f74d1e89132dc0898e7193fde13cfdba6c8158030280b7fba584def",
          "sha256": "feb6afc31052425493e8288fc1b8c5114cf61037d1ede688a097dd439275c588",
          "sha1": "f71a9af1acb6baa9abd715f3138a38ea6093c8ab",
          "md5": "9829c65d4912c64e514f9df8499d551e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-xplat-26.1.2.7-beta-javadoc.jar",
          "url": "moonlightcore-xplat-26.1.2.7-beta-javadoc.jar",
          "size": 5287221,
          "sha512": "551b5afea6ea9a1f4c23a08858d8da6ca2db93725770b3baa7ec6dc1483ae0b20574879701af0fa8cb39f61934a3ad24345b0c02da20879e46d4888c48b5cb28",
          "sha256": "7db03a7fc48dff24b22822fecf3b13edf4cd1a985b23d6101da5d4e079c79cee",
          "sha1": "c98186cd81086e54cf935d9348e65ab2daf1d3d8",
          "md5": "a1f788b987de7efd63f0c84420417a0b"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "moonlightcore-xplat-26.1.2.7-beta-accesstransformer.cfg",
          "url": "moonlightcore-xplat-26.1.2.7-beta-accesstransformer.cfg",
          "size": 0,
          "sha512": "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e",
          "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
          "sha1": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
          "md5": "d41d8cd98f00b204e9800998ecf8427e"
        }
      ]
    }
  ]
}
