{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leoxian.moonlightcore",
    "module": "moonlightcore-xplat",
    "version": "26.1.2.7-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "moonlightcore-xplat-26.1.2.7-beta.jar",
          "url": "moonlightcore-xplat-26.1.2.7-beta.jar",
          "size": 357836,
          "sha512": "95dfccb7b0a0243ce386e3411a116075186589d02ebc182a038f7941efebb607189eca94e49f781703606bc9606bea116e08b33893c66f58c10052cb96c3e395",
          "sha256": "0952bf68c84a9492b6985acd3c710159564ffbcaf7999fff5aa98865b3997544",
          "sha1": "ad4afeb2e41defae1a681e22c46d0ad7b48f7792",
          "md5": "7c377f9b2003a4c9afd762b8c8b6029d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-xplat-26.1.2.7-beta.jar",
          "url": "moonlightcore-xplat-26.1.2.7-beta.jar",
          "size": 357836,
          "sha512": "95dfccb7b0a0243ce386e3411a116075186589d02ebc182a038f7941efebb607189eca94e49f781703606bc9606bea116e08b33893c66f58c10052cb96c3e395",
          "sha256": "0952bf68c84a9492b6985acd3c710159564ffbcaf7999fff5aa98865b3997544",
          "sha1": "ad4afeb2e41defae1a681e22c46d0ad7b48f7792",
          "md5": "7c377f9b2003a4c9afd762b8c8b6029d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-xplat-26.1.2.7-beta-sources.jar",
          "url": "moonlightcore-xplat-26.1.2.7-beta-sources.jar",
          "size": 158619,
          "sha512": "bab71ad33331a10dc2b332be401f4a95b77b4c0b4cc6bfc13945994a2e89237833d2bc03d81d48b1498020cda23fb0fc0fb11beafa8dd1a5da5814f1f4a336eb",
          "sha256": "423e1cb7e9b69ecb7b7abde19583d0fb62ed4de1c5ffc924919726d32f1f66ed",
          "sha1": "414233fe9b7ac73755ce6102e7a430ab590399a6",
          "md5": "6b0b56517c1a3ff5dcd50c8c285f275c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-xplat-26.1.2.7-beta-javadoc.jar",
          "url": "moonlightcore-xplat-26.1.2.7-beta-javadoc.jar",
          "size": 5292536,
          "sha512": "32f70ad55f3a43edf7d62ca970d2c4dd092db494e6dadfb5631a62527fc082ebcef4818ab8c620fb54e53f06bb04d4fcdfe1221e665e6e943fc5f607100557db",
          "sha256": "355a84cc4ab585c557c829f962ab7ffb16c6a17f5523d5a2710cc14378670c18",
          "sha1": "34c8a4a1f22bce05a9d251e61dfe8b613a7c82a2",
          "md5": "50f680e38af331a91aef09218de3b7da"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "moonlightcore-xplat-26.1.2.7-beta-accesstransformer.cfg",
          "url": "moonlightcore-xplat-26.1.2.7-beta-accesstransformer.cfg",
          "size": 0,
          "sha512": "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e",
          "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
          "sha1": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
          "md5": "d41d8cd98f00b204e9800998ecf8427e"
        }
      ]
    }
  ]
}
