{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leoxian.moonlightcore",
    "module": "moonlightcore-xplat",
    "version": "26.1.2.7-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "moonlightcore-xplat-26.1.2.7-beta.jar",
          "url": "moonlightcore-xplat-26.1.2.7-beta.jar",
          "size": 357477,
          "sha512": "a0c062734bc6ffd4e7ca3c435219c29a5c8d1574ce6a4dd7b2af603eb9104841ab496911f992612efba939e880425f7cc2db15f5b6896be20d0649b87e81b435",
          "sha256": "73e3108a78f9865792053eb0f809d2a3f9224d6fe6071e1b0e2f862d170737d4",
          "sha1": "140adaeadaa9219f244095408f481d496607c71f",
          "md5": "9920f0ae699072baba6301d5b96dab99"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-xplat-26.1.2.7-beta.jar",
          "url": "moonlightcore-xplat-26.1.2.7-beta.jar",
          "size": 357477,
          "sha512": "a0c062734bc6ffd4e7ca3c435219c29a5c8d1574ce6a4dd7b2af603eb9104841ab496911f992612efba939e880425f7cc2db15f5b6896be20d0649b87e81b435",
          "sha256": "73e3108a78f9865792053eb0f809d2a3f9224d6fe6071e1b0e2f862d170737d4",
          "sha1": "140adaeadaa9219f244095408f481d496607c71f",
          "md5": "9920f0ae699072baba6301d5b96dab99"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-xplat-26.1.2.7-beta-sources.jar",
          "url": "moonlightcore-xplat-26.1.2.7-beta-sources.jar",
          "size": 158472,
          "sha512": "71c0959d5c492096ce3723eaf46c3ce3f13702ea98ee509037979c870910561d55f14990e905a83ea14e01db60065d3db51682056741cd704e58e0f414c98d27",
          "sha256": "812927223fa8cf48f555e02d4e0f36707e06d3ceefad63d334cb8b8c0966ba5f",
          "sha1": "c61c5d83f24491b1fe1f93e3e622a63d6b3aa254",
          "md5": "261399d86275c0dbc654fc04c4d47c4a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-xplat-26.1.2.7-beta-javadoc.jar",
          "url": "moonlightcore-xplat-26.1.2.7-beta-javadoc.jar",
          "size": 5292440,
          "sha512": "fd5a20c7e05143b7ddc86e67f2ff5fbd39e943ca5010538dc23cfd3c325adc0c3b8d4ea1111c33c339e9bc0a0179fc8c31923459f9e727bb7c26a60e9e3134b2",
          "sha256": "253e5c8b0d1e2cc7d655a8635fb131562ca7cdd264ce02cf4e311ece565febb9",
          "sha1": "ea95af38078f202091e59bb1bc3f65de2a815367",
          "md5": "050c2e42bd8774a54ad5ffe1e98a2c43"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "moonlightcore-xplat-26.1.2.7-beta-accesstransformer.cfg",
          "url": "moonlightcore-xplat-26.1.2.7-beta-accesstransformer.cfg",
          "size": 0,
          "sha512": "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e",
          "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
          "sha1": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
          "md5": "d41d8cd98f00b204e9800998ecf8427e"
        }
      ]
    }
  ]
}
