{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leoxian.moonlightcore",
    "module": "moonlightcore-fabric",
    "version": "26.1.2.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "moonlightcore-fabric-26.1.2.1-beta.jar",
          "url": "moonlightcore-fabric-26.1.2.1-beta.jar",
          "size": 411437,
          "sha512": "40e26d765cfeb03c2936497c198952791ecaea7a27d6f73fba21672b1bc66963ddadce69201621316c5bdcf260cc12fdbe11c291eb6d2e771d83186918ad8e34",
          "sha256": "9858d791e8a95c56afa61931663b570cc74043aa3234c3dbca62ce94e91ce14a",
          "sha1": "812bd8e617759061507addfd7085fa4f425d5fe7",
          "md5": "eff961ff53e8c1648051dd47909e2ac7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.149.0+26.1.2"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "moonlightcore-fabric-26.1.2.1-beta.jar",
          "url": "moonlightcore-fabric-26.1.2.1-beta.jar",
          "size": 411437,
          "sha512": "40e26d765cfeb03c2936497c198952791ecaea7a27d6f73fba21672b1bc66963ddadce69201621316c5bdcf260cc12fdbe11c291eb6d2e771d83186918ad8e34",
          "sha256": "9858d791e8a95c56afa61931663b570cc74043aa3234c3dbca62ce94e91ce14a",
          "sha1": "812bd8e617759061507addfd7085fa4f425d5fe7",
          "md5": "eff961ff53e8c1648051dd47909e2ac7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-fabric-26.1.2.1-beta-sources.jar",
          "url": "moonlightcore-fabric-26.1.2.1-beta-sources.jar",
          "size": 168174,
          "sha512": "853c1d13b5d0b7267f465452226f3acedf7ca586ce0c5524dcbfae80e5b089f248f55be5663d66f31e2b58e79e520f9fec98f9ba3ffb1e1d13cb42fddce6df6d",
          "sha256": "37bbee75b32f92fa45763d5b7e6139d727aa895c345a66e0883db314bdf55ce6",
          "sha1": "dc63d5975e072e2592d3b4ba96f2a7a8bdbd8521",
          "md5": "c341e85e3a54cb4b4f07d04b4962de1b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-fabric-26.1.2.1-beta-javadoc.jar",
          "url": "moonlightcore-fabric-26.1.2.1-beta-javadoc.jar",
          "size": 5318611,
          "sha512": "e63daa80713f835b2009b0a912cd5827a138f170915b976ff3849ecf9ca7bf0ea617ebf339ff1a07943a21686fbc116849054192b86b339e57805699358a24dd",
          "sha256": "3872d9dbb12b7494358eaace63f59c6e4b4d4f76852957bad26446076d5f524d",
          "sha1": "5883c9d38e1136b502dd0f91a787efe216047eaa",
          "md5": "bbf968921f818a3923df7b24ab471d5e"
        }
      ]
    }
  ]
}
