{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leoxian.moonlightcore",
    "module": "moonlightcore-fabric",
    "version": "26.1.2.7-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "moonlightcore-fabric-26.1.2.7-beta.jar",
          "url": "moonlightcore-fabric-26.1.2.7-beta.jar",
          "size": 490225,
          "sha512": "fe0967a651c4c144856cbedb162c8c5140519380ed0e49c504a2a7cfbc792124059ccf0ab67401c980d3808e094aa1e24ffe57ba7a4445866a16f4daa37fd4bb",
          "sha256": "377f8cb13f60bcd15e25919b81d508d3c06f2c01639a905f9e414597e9942d71",
          "sha1": "fa1e7576d1970a526e6999452a14bf1340f466b7",
          "md5": "be2f3b32591bfd794f825f4e8748c29a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.149.0+26.1.2"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "moonlightcore-fabric-26.1.2.7-beta.jar",
          "url": "moonlightcore-fabric-26.1.2.7-beta.jar",
          "size": 490225,
          "sha512": "fe0967a651c4c144856cbedb162c8c5140519380ed0e49c504a2a7cfbc792124059ccf0ab67401c980d3808e094aa1e24ffe57ba7a4445866a16f4daa37fd4bb",
          "sha256": "377f8cb13f60bcd15e25919b81d508d3c06f2c01639a905f9e414597e9942d71",
          "sha1": "fa1e7576d1970a526e6999452a14bf1340f466b7",
          "md5": "be2f3b32591bfd794f825f4e8748c29a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-fabric-26.1.2.7-beta-sources.jar",
          "url": "moonlightcore-fabric-26.1.2.7-beta-sources.jar",
          "size": 214282,
          "sha512": "c350d1ae0d7f01cf6e88e573ff048cdcabac10b834877b55a02b5925170482a217e7d4ee1faf14cb641f60a267b56a10774ab04a3aa02045b20bb10f76305991",
          "sha256": "7b964e69d1895129ea408f92cf850c3c39d340dffb70aaf65fdf5ffe9fb387e0",
          "sha1": "16cd827cc01fde93025961adc679c0f5f4fc532f",
          "md5": "d2e5e04bf132518fe72a185e5a9f02e5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-fabric-26.1.2.7-beta-javadoc.jar",
          "url": "moonlightcore-fabric-26.1.2.7-beta-javadoc.jar",
          "size": 5642417,
          "sha512": "22c41668ded20f38e05da98f139248407933c8ca79b3e627c61f5af389cc41f88c4dfe70e3c852757dcd65f45a67c694221c80a870bc56b3638f9c2fc45a1432",
          "sha256": "cd0b94cb7b512d0bc876af95f3b9c59fd593561c847a96993e99192a96b288fd",
          "sha1": "8c0544ad7fb766035cee937b267f449d0aa43d26",
          "md5": "0c00b3b26dbe0d4eb08c0e9ea58d57c5"
        }
      ]
    }
  ]
}
