{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leoxian.moonlightcore",
    "module": "moonlightcore-fabric",
    "version": "26.1.2.7-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "moonlightcore-fabric-26.1.2.7-beta.jar",
          "url": "moonlightcore-fabric-26.1.2.7-beta.jar",
          "size": 484467,
          "sha512": "3ec3ff052c7b780c31126bb70855cad8001b62e384fff12b39361d12706da9c79bef94fac6b3cfffd5ff8058cdcfa74be59fd6ad5775e484347aa35eeb9e56f6",
          "sha256": "b3d547c269eebdad1c06cb07e364aaa42096ffc051c5131a5e3c7fec1b634061",
          "sha1": "ed900b27a54fb3996cc361ad6b67807730138e77",
          "md5": "e22c6e1dbab50e10adc1254da2911655"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.149.0+26.1.2"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "moonlightcore-fabric-26.1.2.7-beta.jar",
          "url": "moonlightcore-fabric-26.1.2.7-beta.jar",
          "size": 484467,
          "sha512": "3ec3ff052c7b780c31126bb70855cad8001b62e384fff12b39361d12706da9c79bef94fac6b3cfffd5ff8058cdcfa74be59fd6ad5775e484347aa35eeb9e56f6",
          "sha256": "b3d547c269eebdad1c06cb07e364aaa42096ffc051c5131a5e3c7fec1b634061",
          "sha1": "ed900b27a54fb3996cc361ad6b67807730138e77",
          "md5": "e22c6e1dbab50e10adc1254da2911655"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-fabric-26.1.2.7-beta-sources.jar",
          "url": "moonlightcore-fabric-26.1.2.7-beta-sources.jar",
          "size": 212808,
          "sha512": "87451f711b60d687edf045dc4b797871463153ad4123cbe63c6b4f5a8215371ba9bb366908e3e0b87b01f9d7e4db056039a18a811ca3cbfe8b641385c14e0615",
          "sha256": "2f55f316e30305d7bbac312b49cce315b1a653d256ee6f192574d53808ac5059",
          "sha1": "ebdda072d34d22e5c7d5adc6b95f8d21d85f87dc",
          "md5": "24bd22cf731ea660a86805609e361b43"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-fabric-26.1.2.7-beta-javadoc.jar",
          "url": "moonlightcore-fabric-26.1.2.7-beta-javadoc.jar",
          "size": 5627201,
          "sha512": "b5e3b2350ee02feef558d8bd96353f99d20e13ba3ddb4284888bce1c48735e8aab20be6423b2f871b5336fbdebc757e33fa817a3b49f82cdf54119c1a32ae31f",
          "sha256": "804a6221f5d6aea4591dd64de7e036edcf07c4572d812bfa97094de7c5629499",
          "sha1": "d605579dd39b380b59de67392ed9404b141d0573",
          "md5": "44ffe3cec3b00c1f0c90d0a478893ed5"
        }
      ]
    }
  ]
}
