{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leoxian.moonlightcore",
    "module": "moonlightcore-neoforge",
    "version": "26.1.2.8-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "moonlightcore-neoforge-26.1.2.8-beta.jar",
          "url": "moonlightcore-neoforge-26.1.2.8-beta.jar",
          "size": 484330,
          "sha512": "e0bb2766a655a74cff9df6a98a4a1f874be9d6cfca0ab792c5120c97d6e59b0fd51e5e3e5ccba2bedb5bf7ea192f80026faa52fec43f8a015a738b3c2534a271",
          "sha256": "dcac2f79d20482bcf35d2cb01bbe1a7ac6e859e90f0fe2607ec40738279cd42f",
          "sha1": "3cadb12682a513f41560ba44ffac76136b8dc720",
          "md5": "9c84d079998b5e189e5f3c85d4be0e4d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-neoforge-26.1.2.8-beta.jar",
          "url": "moonlightcore-neoforge-26.1.2.8-beta.jar",
          "size": 484330,
          "sha512": "e0bb2766a655a74cff9df6a98a4a1f874be9d6cfca0ab792c5120c97d6e59b0fd51e5e3e5ccba2bedb5bf7ea192f80026faa52fec43f8a015a738b3c2534a271",
          "sha256": "dcac2f79d20482bcf35d2cb01bbe1a7ac6e859e90f0fe2607ec40738279cd42f",
          "sha1": "3cadb12682a513f41560ba44ffac76136b8dc720",
          "md5": "9c84d079998b5e189e5f3c85d4be0e4d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-neoforge-26.1.2.8-beta-sources.jar",
          "url": "moonlightcore-neoforge-26.1.2.8-beta-sources.jar",
          "size": 208198,
          "sha512": "1d57990485f6f4c7ab6d4b7b223c2e7d978515163042f6fbf65d331830f3ac0e364d7d003e107866447b758801e5d1ee2ca4fa7bc348c5723135d97d524d1680",
          "sha256": "8861c4b29d2b370a940fca3adeba73da96b19da4cbd29f6a0a00d89f98157e33",
          "sha1": "994adaa6a524564a1019918e1c01292679366874",
          "md5": "44e59a6eee2347d6ce5d9f3e0e517822"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-neoforge-26.1.2.8-beta-javadoc.jar",
          "url": "moonlightcore-neoforge-26.1.2.8-beta-javadoc.jar",
          "size": 5596002,
          "sha512": "8315752c0a5e1bd89b36dd6b9d893f7e42dae48e0031f3bec51aea78697e53fe80943d064da8f3cd00009eadf96a18c2d6ce07cb5bb01b35cc385f43b7d06e9d",
          "sha256": "bcce83e6f8acd675adea3813019f7632a509b818e75f059b04aa1c7d971664a8",
          "sha1": "b4a735e4ff181827c71e393bb2eea9065846c606",
          "md5": "1799da079570e2804c2369a5426fedff"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "moonlightcore-neoforge-26.1.2.8-beta-accesstransformer.cfg",
          "url": "moonlightcore-neoforge-26.1.2.8-beta-accesstransformer.cfg",
          "size": 0,
          "sha512": "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e",
          "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
          "sha1": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
          "md5": "d41d8cd98f00b204e9800998ecf8427e"
        }
      ]
    }
  ]
}
