{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leoxian.moonlightcore",
    "module": "moonlightcore-xplat",
    "version": "26.1.2.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "moonlightcore-xplat-26.1.2.1-beta.jar",
          "url": "moonlightcore-xplat-26.1.2.1-beta.jar",
          "size": 306142,
          "sha512": "353eadf26f2a64923562cb61a01e64f536e6d7ebf6dab737b642b53003f937718b6b199f481df173dfb319785cd4dcac8f14518c3d2a05c154b10c5278d4949e",
          "sha256": "06fc04bfc68dcfe9d7d670feae706f9dbbc3f2fd75a06477849dd139f11b5962",
          "sha1": "f6a11ab6a763090e6303251b152e031dbf4e11bc",
          "md5": "8e724b342e4937aa4ccc64e2e4bde810"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-xplat-26.1.2.1-beta.jar",
          "url": "moonlightcore-xplat-26.1.2.1-beta.jar",
          "size": 306142,
          "sha512": "353eadf26f2a64923562cb61a01e64f536e6d7ebf6dab737b642b53003f937718b6b199f481df173dfb319785cd4dcac8f14518c3d2a05c154b10c5278d4949e",
          "sha256": "06fc04bfc68dcfe9d7d670feae706f9dbbc3f2fd75a06477849dd139f11b5962",
          "sha1": "f6a11ab6a763090e6303251b152e031dbf4e11bc",
          "md5": "8e724b342e4937aa4ccc64e2e4bde810"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-xplat-26.1.2.1-beta-sources.jar",
          "url": "moonlightcore-xplat-26.1.2.1-beta-sources.jar",
          "size": 130353,
          "sha512": "98be509a4fb2a85bdb9e0b16a0b309b2c0ece31db84f4cd95bfc3f0c9583542d456d94f21f1a79d722b2b018eb62ca0abb52c2aef14c8737e93c6e83d1f64449",
          "sha256": "17adce4ba1a92158f29872690912adefd882ee993497521b8f0d8a727c5383be",
          "sha1": "fc3f9594ebcc279b1c8b4dd163ad936254f50c6d",
          "md5": "83d5ec601418fcedf6f02bbf3a6b18ee"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-xplat-26.1.2.1-beta-javadoc.jar",
          "url": "moonlightcore-xplat-26.1.2.1-beta-javadoc.jar",
          "size": 5147174,
          "sha512": "eba89322891113be0b05a76ae38f0c57a91bd39930a5b10954d89c1e83e8f22b58dc8d31268a9eedcaf1df09f6319c09117e514d24fd51f9c3a2573617eff49e",
          "sha256": "bdb6816b84722ae1d36cff65a742812ba24b2dfd99f65066d04bf5930c1fa9d7",
          "sha1": "6dd587099b66485825f37fc286dc834b0cfa8a4f",
          "md5": "3328b620a6e5963e2184a6bffac84742"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "moonlightcore-xplat-26.1.2.1-beta-accesstransformer.cfg",
          "url": "moonlightcore-xplat-26.1.2.1-beta-accesstransformer.cfg",
          "size": 0,
          "sha512": "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e",
          "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
          "sha1": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
          "md5": "d41d8cd98f00b204e9800998ecf8427e"
        }
      ]
    }
  ]
}
