{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leoxian.moonlightcore",
    "module": "moonlightcore-neoforge",
    "version": "26.1.2.7-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "moonlightcore-neoforge-26.1.2.7-beta.jar",
          "url": "moonlightcore-neoforge-26.1.2.7-beta.jar",
          "size": 485964,
          "sha512": "0827867e7aa75510c9320979acde487b3c60416edc4e49b2eac4947dcc308e581c58145a4e7ef0925b2c2e80036b1c605e7a206a089e631f9a532ef75975a151",
          "sha256": "38fe2398ddfa13da77d99a63dbe4e25b27a90b7edf189b65450efa67faacb013",
          "sha1": "76e6d5cf480b82e373aeb5533f12b4afcc3a927b",
          "md5": "45eae2ce0cd093b7e987cc8d666ace5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-neoforge-26.1.2.7-beta.jar",
          "url": "moonlightcore-neoforge-26.1.2.7-beta.jar",
          "size": 485964,
          "sha512": "0827867e7aa75510c9320979acde487b3c60416edc4e49b2eac4947dcc308e581c58145a4e7ef0925b2c2e80036b1c605e7a206a089e631f9a532ef75975a151",
          "sha256": "38fe2398ddfa13da77d99a63dbe4e25b27a90b7edf189b65450efa67faacb013",
          "sha1": "76e6d5cf480b82e373aeb5533f12b4afcc3a927b",
          "md5": "45eae2ce0cd093b7e987cc8d666ace5c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-neoforge-26.1.2.7-beta-sources.jar",
          "url": "moonlightcore-neoforge-26.1.2.7-beta-sources.jar",
          "size": 208605,
          "sha512": "371786fdcbfb2e30670f748e30f20ca2ec365b8ff6bbbb60b308db41e20426b8f70c9602b9e1adaacd7d2d1e3a555bdfe63014e76d5aa78cd504963c114fd69e",
          "sha256": "1ceb7bfa9385e0d2c634899a2b74ab328df8b189b95fe265ffd234ef28efdc4d",
          "sha1": "5f72675e1d77ff0dfe461eba15d54bb6d71ea94f",
          "md5": "296ffe6bd1bfd87a0a5d345f21ef62ee"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-neoforge-26.1.2.7-beta-javadoc.jar",
          "url": "moonlightcore-neoforge-26.1.2.7-beta-javadoc.jar",
          "size": 5598721,
          "sha512": "0a7915e27ee10572939c34811d6f9d01ce3be4bf63f01ce767da670a67eca6e7b1a06c4330cb05b628b2c814a04138a142b4f52e5d6ec6bc9a9f816793b65298",
          "sha256": "87eda44e1b1f1c849fa238384c0fa6427e24caec3a9b8e24374f9196e4dd280e",
          "sha1": "2d1b15ac823733cd81b703eb1caaa94b0b93ff6a",
          "md5": "40686afa9235a724508c6ba78d25d40c"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "moonlightcore-neoforge-26.1.2.7-beta-accesstransformer.cfg",
          "url": "moonlightcore-neoforge-26.1.2.7-beta-accesstransformer.cfg",
          "size": 0,
          "sha512": "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e",
          "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
          "sha1": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
          "md5": "d41d8cd98f00b204e9800998ecf8427e"
        }
      ]
    }
  ]
}
