{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leoxian.moonlightcore",
    "module": "moonlightcore-neoforge",
    "version": "26.1.2.7-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "moonlightcore-neoforge-26.1.2.7-beta.jar",
          "url": "moonlightcore-neoforge-26.1.2.7-beta.jar",
          "size": 489206,
          "sha512": "a37c847b70b2e338764a705acde0bb3b8de597b13d0dfbf8a55e44a13a68075c655ed6d97f0eeb5fa686eeebc1e4374289a3ee3f42fdf20efdde7de64cba3553",
          "sha256": "832894c4cb16655bfd4209f0f151b6480c8e76756f2acea7faff8ae3eeb4c332",
          "sha1": "9f4f01243d04617cf30edd31820a84391f6fe262",
          "md5": "12ef4b298bc692f66a019e483882db81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-neoforge-26.1.2.7-beta.jar",
          "url": "moonlightcore-neoforge-26.1.2.7-beta.jar",
          "size": 489206,
          "sha512": "a37c847b70b2e338764a705acde0bb3b8de597b13d0dfbf8a55e44a13a68075c655ed6d97f0eeb5fa686eeebc1e4374289a3ee3f42fdf20efdde7de64cba3553",
          "sha256": "832894c4cb16655bfd4209f0f151b6480c8e76756f2acea7faff8ae3eeb4c332",
          "sha1": "9f4f01243d04617cf30edd31820a84391f6fe262",
          "md5": "12ef4b298bc692f66a019e483882db81"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-neoforge-26.1.2.7-beta-sources.jar",
          "url": "moonlightcore-neoforge-26.1.2.7-beta-sources.jar",
          "size": 209558,
          "sha512": "2e3431b04cb4ea5c7c7cdb1876fa56fc798d7e71e7b23a683f51a33e133b14befc3a270a902d2cceef93ffabc14df29bdb1eb457f441ee6d96895d455f5760e8",
          "sha256": "3300ffc86553653c31e5ff5ce15de23422451dd1f23dd3ba794da8eca34b834f",
          "sha1": "322d72b2b8badfa4c156db67ebb65262d0c43116",
          "md5": "8f83f62339ad07e1e710e68bed9930ce"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-neoforge-26.1.2.7-beta-javadoc.jar",
          "url": "moonlightcore-neoforge-26.1.2.7-beta-javadoc.jar",
          "size": 5604678,
          "sha512": "c063925c00b5f07a44aa88d22d7d433e20752cad09619d08eff0160c9594e153bc68b6017f61288f775ed4518f5c332499294b11191110acc844aa7be1c2f1a2",
          "sha256": "75d7b19d23b897d6b966e8d4f26f2a5fc88ee62eaa32d14483b41f2e4efa1fbe",
          "sha1": "f2a24cbb3a6db2a89d0eb5fa9b525407ce3edb59",
          "md5": "c5586410dc9857885301c5809a0c7a6a"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "moonlightcore-neoforge-26.1.2.7-beta-accesstransformer.cfg",
          "url": "moonlightcore-neoforge-26.1.2.7-beta-accesstransformer.cfg",
          "size": 0,
          "sha512": "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e",
          "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
          "sha1": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
          "md5": "d41d8cd98f00b204e9800998ecf8427e"
        }
      ]
    }
  ]
}
