{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leoxian.moonlightcore",
    "module": "moonlightcore-fabric",
    "version": "26.1.2.8-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "moonlightcore-fabric-26.1.2.8-beta.jar",
          "url": "moonlightcore-fabric-26.1.2.8-beta.jar",
          "size": 482818,
          "sha512": "15d2925fcf955837dcd4154613069b456e7436d920d589486b17be5bcbcb6b6c08f8358f7598c1d22edf07e6f4f0ad844edc0ce307fa2862f56b25ab75f0126f",
          "sha256": "083e22cf845b267c2994095215d0375b44da10049acc8126772619a74ea54d4f",
          "sha1": "454a26589c36b394634d0708316d1ed486f0d090",
          "md5": "296b7f5fada1a505d40b8f19e2f00cc2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.149.0+26.1.2"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "moonlightcore-fabric-26.1.2.8-beta.jar",
          "url": "moonlightcore-fabric-26.1.2.8-beta.jar",
          "size": 482818,
          "sha512": "15d2925fcf955837dcd4154613069b456e7436d920d589486b17be5bcbcb6b6c08f8358f7598c1d22edf07e6f4f0ad844edc0ce307fa2862f56b25ab75f0126f",
          "sha256": "083e22cf845b267c2994095215d0375b44da10049acc8126772619a74ea54d4f",
          "sha1": "454a26589c36b394634d0708316d1ed486f0d090",
          "md5": "296b7f5fada1a505d40b8f19e2f00cc2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-fabric-26.1.2.8-beta-sources.jar",
          "url": "moonlightcore-fabric-26.1.2.8-beta-sources.jar",
          "size": 212401,
          "sha512": "9cadfa09851618007ca8c6fe2fe45b61ebbef7ef30195c14d0881ac49b9ef6f1639ad26973d0e537ed515a5e0e6e5b8ed0ab914cfe2283ee6f9aeeb5478f09cc",
          "sha256": "526eaaf438e92c4213af04e3eb471e82d14ca8b2fc1e6fe14faec5a32c3d8d76",
          "sha1": "6d41345490837d352e480fd05630db1976be908f",
          "md5": "9acb6773dbc8210ff2f66e5bd38ff536"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlightcore-fabric-26.1.2.8-beta-javadoc.jar",
          "url": "moonlightcore-fabric-26.1.2.8-beta-javadoc.jar",
          "size": 5624499,
          "sha512": "6bdc0ae4ad6590f4a19a800568fe915a2d4489e106f9a379ef67fb9d0cf386f932368f71f98370f1333fff4ca12b6d1f968cb03334274ab8f02355f75bb528b4",
          "sha256": "db6ee2b13b4d796ac397de3cd86a70fc9e73f24a9bc72eb294d028b657116582",
          "sha1": "9910e0f88ae0334ff062ead81eac1dc6c00c1d33",
          "md5": "90d9fa2c271151dbb63c8ac4bb1e34d3"
        }
      ]
    }
  ]
}
